# Find TINYXML2
# --------------------------------
#MESSAGE("DBG Find TINYXML2 package")


SET(TINYXML2_INSTALL_DIR $ENV{TINYXML2_DIR})
SET(TINYXML2_V $ENV{TINYXML2_VERSION}) 

IF (TINYXML2_INSTALL_DIR)
  MESSAGE(STATUS "FindTINYXML2.cmake: TINYXML2_INSTALL_DIR variable points to ${TINYXML2_INSTALL_DIR}")
ELSE(TINYXML2_INSTALL_DIR)
      MESSAGE(FATAL_ERROR "FindTINYXML2.cmake: TINYXML2_INSTALL_DIR not defined. Please set it")
ENDIF(TINYXML2_INSTALL_DIR)

IF (TINYXML2_V)
  MESSAGE(STATUS "FindTINYXML2.cmake: TINYXML2_VERSION variable points to ${TINYXML2_V}")
ELSE(TINYXML2_V)
      MESSAGE(FATAL_ERROR "FindTINYXML2.cmake: TINYXML2_VERSION not defined. Please set it")
ENDIF(TINYXML2_V)

SET(TINYXML2_LIB_DIR ${TINYXML2_INSTALL_DIR}/lib)
SET(TINYXML2_INCLUDE_DIR ${TINYXML2_INSTALL_DIR}/include)
SET(TINYXML2_INCLUDES "-I${TINYXML2_INCLUDE_DIR}")
SET(TINYXML2_LIBRARIES "-L${TINYXML2_LIB_DIR}/ -ltinyxml${TINYXML2_V}") 
