# Find CLHEP
# --------------------------------
#MESSAGE("DBG Find CLHEP package")


SET(CLHEP_INSTALL_DIR $ENV{CLHEP_DIR})
SET(CLHEP_V $ENV{CLHEP_VERSION}) 

IF (CLHEP_INSTALL_DIR)
  MESSAGE(STATUS "FindCLHEP.cmake: CLHEP_INSTALL_DIR variable points to ${CLHEP_INSTALL_DIR}")
ELSE(CLHEP_INSTALL_DIR)
      MESSAGE(FATAL_ERROR "FindCLHEP.cmake: CLHEP_INSTALL_DIR not defined. Please set it")
ENDIF(CLHEP_INSTALL_DIR)

IF (CLHEP_V)
  MESSAGE(STATUS "FindCLHEP.cmake: CLHEP_VERSION variable points to ${CLHEP_V}")
ELSE(CLHEP_V)
      MESSAGE(FATAL_ERROR "FindCLHEP.cmake: CLHEP_VERSION not defined. Please set it")
ENDIF(CLHEP_V)

SET(CLHEP_LIB_DIR ${CLHEP_INSTALL_DIR}/lib)
SET(CLHEP_INCLUDE_DIR ${CLHEP_INSTALL_DIR}/include)
SET(CLHEP_INCLUDES "-I${CLHEP_INCLUDE_DIR}")
SET(CLHEP_LIBRARIES "-L${CLHEP_LIB_DIR}/ -lCLHEP-${CLHEP_V}") 
