# Find gate
# --------------------------------
#MESSAGE("DBG Find LOG4CPP package")


SET(GATE_INSTALL_DIR $ENV{GATE_DIR}) 

IF (GATE_INSTALL_DIR)
  MESSAGE(STATUS "FindGATE.cmake: GATE_INSTALL_DIR variable points to ${GATE_INSTALL_DIR}")
ELSE(GATE_INSTALL_DIR)
      MESSAGE(FATAL_ERROR "FindGATE.cmake: GATE_INSTALL_DIR not defined. Please set it")
ENDIF(GATE_INSTALL_DIR)

SET(GATE_LIB_DIR ${GATE_INSTALL_DIR}/lib)
SET(GATE_INCLUDE_DIR ${GATE_INSTALL_DIR}/include)
SET(GATE_INCLUDES "-I${GATE_INCLUDE_DIR}")
SET(GATE_LIBRARIES "-L${GATE_LIB_DIR}/ -lGATE") 
