# Find RECPACK
# --------------------------------
#MESSAGE("DBG Find RECPACK package")


SET(RECPACK_INSTALL_DIR $ENV{RECPACK_DIR}) 

IF (RECPACK_INSTALL_DIR)
  MESSAGE(STATUS "FindRECPACK.cmake: RECPACK_INSTALL_DIR variable points to ${RECPACK_INSTALL_DIR}")
ELSE(RECPACK_INSTALL_DIR)
      MESSAGE(FATAL_ERROR "FindRECPACK.cmake: RECPACK_INSTALL_DIR not defined. Please set it")
ENDIF(RECPACK_INSTALL_DIR)

SET(RECPACK_LIB_DIR ${RECPACK_INSTALL_DIR}/lib)
SET(RECPACK_INCLUDE_DIR ${RECPACK_INSTALL_DIR}/include)
SET(RECPACK_INCLUDES "-I${RECPACK_INCLUDE_DIR}")
SET(RECPACK_LIBRARIES "-L${RECPACK_LIB_DIR}/ -lrecpack") 
