# Find LOG4CPP
# --------------------------------
#MESSAGE("DBG Find LOG4CPP package")


SET(LOG4CPP_INSTALL_DIR $ENV{LOG4CPP_DIR}) 

IF (LOG4CPP_INSTALL_DIR)
  MESSAGE(STATUS "FindLOG4CPP.cmake: LOG4CPP_INSTALL_DIR variable points to ${LOG4CPP_INSTALL_DIR}")
ELSE(LOG4CPP_INSTALL_DIR)
      MESSAGE(FATAL_ERROR "FindLOG4CPP.cmake: LOG4CPP_INSTALL_DIR not defined. Please set it")
ENDIF(LOG4CPP_INSTALL_DIR)

SET(LOG4CPP_LIB_DIR ${LOG4CPP_INSTALL_DIR}/lib)
SET(LOG4CPP_INCLUDE_DIR ${LOG4CPP_INSTALL_DIR}/include)
SET(LOG4CPP_INCLUDES "-I${LOG4CPP_INCLUDE_DIR}")
SET(LOG4CPP_LIBRARIES "-L${LOG4CPP_LIB_DIR}/ -llog4cpp") 
