# Find PAOLINA
# --------------------------------
#MESSAGE("DBG Find PAOLINA package")


SET(PAOLINA_INSTALL_DIR $ENV{PAOLINA_DIR}) 

IF (PAOLINA_INSTALL_DIR)
  MESSAGE(STATUS "FindPAOLINA.cmake: PAOLINA_INSTALL_DIR variable points to ${PAOLINA_INSTALL_DIR}")
ELSE(PAOLINA_INSTALL_DIR)
      MESSAGE(FATAL_ERROR "FindPAOLINA.cmake: PAOLINA_INSTALL_DIR not defined. Please set it")
ENDIF(PAOLINA_INSTALL_DIR)

SET(PAOLINA_LIB_DIR ${PAOLINA_INSTALL_DIR})
SET(PAOLINA_INCLUDE_DIR ${PAOLINA_INSTALL_DIR})
SET(PAOLINA_INCLUDES "-I${PAOLINA_INCLUDE_DIR}")
SET(PAOLINA_LIBRARIES "-L${PAOLINA_LIB_DIR}/ -lpaolina") 
